#!/usr/bin/env python3.6
from __future__ import print_function
from sys import argv
import sys


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def add_xor(path):
    file_open = open(path, "r")
    first_value = file_open.readline().replace('\n', '')
    second_value = file_open.readline().replace('\n', '')
    if len(first_value) != len(second_value) or len(first_value) % 2 == 1 or len(first_value) == 0 or len(second_value) == 0:
        sys.exit(84)
    to_print = ''.join(hex(int(a, 16) ^ int(b, 16))[2:] for a, b in zip(first_value, second_value))
    print(to_print.upper())


if __name__ == "__main__":
    try:
        add_xor(argv[1])
    except Exception as e:
        eprint(e)
        sys.exit(84)
    sys.exit(0)
