#!/usr/bin/env python3.6
from __future__ import print_function
import sys


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def main():
    sys.exit(84)


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        eprint(e)
        sys.exit(84)
    sys.exit(0)